# Generated by Django 5.0.1 on 2024-02-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SensorData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("packet_number", models.IntegerField()),
                ("node", models.IntegerField()),
                ("tx_id", models.IntegerField()),
                ("time", models.DateTimeField(auto_now_add=True)),
                ("delta_time", models.DurationField()),
                ("rssi", models.FloatField()),
                ("temperature", models.FloatField()),
                ("humidity", models.IntegerField()),
                ("light", models.IntegerField()),
                ("external_voltage", models.FloatField()),
            ],
        ),
    ]
