# Generated by Django 5.0.1 on 2024-02-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("charts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensordata",
            name="delta_time",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sensordata",
            name="external_voltage",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sensordata",
            name="humidity",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sensordata",
            name="light",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sensordata",
            name="rssi",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sensordata",
            name="temperature",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
