# Generated by Django 5.0.1 on 2024-02-17 18:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("charts", "0002_alter_sensordata_delta_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sensordata",
            name="tx_id",
        ),
    ]
