apiVersion: v1
kind: Service
metadata:
  labels:
    app: django-app
  name: django-service
spec:
  type: NodePort
  ports:
  - name: "django-service-8000"
    port: 8000
    targetPort: 8000
  selector:
    app: django-app
